Fixes for AndroidStudio
When trying to build MiniBrowser with Android studio a
java.lang.NoSuchMethodError was generated. Apparently it was caused by a
binary incompatibility between Gradle 9.3.1 and AGP 8.8.0. AGP 9.0
removed several APIs that AGP depends on, meaning that it basically
breaks compatibility with AGP < 9.

AGP >= 9.0 is not strictly required so it seems a good idea to downgrade
the version in order to have proper builds in the most popular IDE for
Android development.

Apart from that, and while not strictly needed, we're migrating
gradle.afterProject to a more modern approach of doing things. Modifying
the ABI filters inside afterProject is considered a legacy approach that
could lead to race conditions in the build (or rather the Sync phase).
By moving the logic into the android block we ensure that AndroidStudio
can see the configuration during the sync phase.